- name: Install ClusterShell
  ansible.builtin.package:
    name: "{{
      clustershell_packages +
      clustershell_sshpass | ternary(['sshpass'], []) +
      clustershell_sudo | ternary(['sudo'], [])
    }}"
    state: present

- name: Set default group name
  ansible.builtin.lineinfile:
    path: /etc/clustershell/groups.conf
    regexp: '^default:'
    line: 'default: ansible'

- name: Define default groups
  ansible.builtin.template:
    src: ansible.yaml.j2
    dest: /etc/clustershell/groups.d/ansible.yaml
    owner: root
    group: root
    mode: "0644"

- name: Configure group bindings from examples
  loop: "{{ clustershell_group_bindings }}"
  loop_control:
    label: "Install /etc/clustershell/groups.conf.d/{{ item }}.conf"
  ansible.builtin.copy:
    remote_src: true
    src: /etc/clustershell/groups.conf.d/{{ item }}.conf.example
    dest: /etc/clustershell/groups.conf.d/{{ item }}.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure custom group bindings
  loop: "{{ clustershell_group_bindings_custom }}"
  loop_control:
    label: "Install /etc/clustershell/groups.conf.d/{{ item.name }}.conf"
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: /etc/clustershell/groups.conf.d/{{ item.name }}.conf
    owner: root
    group: root
    mode: "0644"

- name: Remove group bindings
  loop: "{{ clustershell_group_bindings_remove }}"
  loop_control:
    label: "Remove /etc/clustershell/groups.conf.d/{{ item }}.conf"
  ansible.builtin.file:
    path: /etc/clustershell/groups.conf.d/{{ item }}.conf
    state: absent

- name: Ensure clush.conf.d exists
  when: clustershell_sshpass | bool or clustershell_sudo | bool
  ansible.builtin.file:
    path: /etc/clustershell/clush.conf.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure sshpass mode
  when: clustershell_sshpass | bool
  ansible.builtin.template:
    src: sshpass.conf.j2
    dest: /etc/clustershell/clush.conf.d/sshpass.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure sudo mode
  when: clustershell_sudo | bool
  ansible.builtin.template:
    src: sudo.conf.j2
    dest: /etc/clustershell/clush.conf.d/sudo.conf
    owner: root
    group: root
    mode: "0644"
