- name: Install ClusterShell
  ansible.builtin.package:
    name: "{{ clustershell_package }}"
    state: present

- name: Set default group name
  ansible.builtin.lineinfile:
    path: /etc/clustershell/groups.conf
    regexp: '^default:'
    line: 'default: ansible'

- name: Define default groups
  ansible.builtin.template:
    src: ansible.yaml.j2
    dest: /etc/clustershell/groups.d/ansible.yaml
    owner: root
    group: root
    mode: 0644
