---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${CONTAINER:-ubuntu:bionic}"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
