---
name: clustershell unit testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  molecule:
    name: ${{ matrix.distro }} - Molecule tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - geerlingguy/docker-centos7-ansible:latest
          - geerlingguy/docker-centos8-ansible:latest
          - geerlingguy/docker-debian10-ansible:latest
          - geerlingguy/docker-debian11-ansible:latest
          - geerlingguy/docker-ubuntu1804-ansible:latest
          - geerlingguy/docker-ubuntu2004-ansible:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'clustershell'

      - name: Setup python environment
        uses: actions/setup-python@v2

      - name: Install test dependencies
        run: pip3 install tox

      - name: Run molecule tests
        run: tox
        working-directory: clustershell
        env:
          CONTAINER: ${{ matrix.distro }}
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
