---
name: clustershell unit testing
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Every Monday at 7:47 EST
    - cron: "47 11 * * 1"

jobs:
  molecule:
    name: ${{ matrix.distro }} - ${{ matrix.scenario }} - Molecule tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian11
          - debian12
          - rockylinux9
          - ubuntu2204
          - ubuntu2404
        scenario:
          - default
          - sshpass
          - sudo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'clustershell'

      - name: Setup python environment
        uses: actions/setup-python@v5

      - name: Install test dependencies
        run: pip3 install tox

      - name: Run molecule tests
        run: tox
        working-directory: clustershell
        env:
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          PY_COLORS: 1
